version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"

  db:
    image: postgres:10.5
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - "./app/redis:/data"

  worker:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - APP_SECRET=$APP_SECRET
    volumes:
      - ".:/var/app"
    depends_on:
      - "redis"
    depends_on:
      - web
      - db
    links:
      - db
      - redis

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
      
volumes:
  postgresql-data:
    driver: local